module/botswana:
    on_startup:
        run: echo 'Greetings from Botswana!'

module/ghana:
    on_startup:
        run: echo 'Greetings from Ghana!'

context/geography:
    botswana:
        capitol: Gaborone

    ghana:
        capitol: Accra
